Order items text
 "Rava Dosa", "South Indian",
 "Masala Dosa", "South Indian",
 "Sada Dosa", "South Indian",
 "Idli Plate", "South Indian",
 "Vada Plate", "South Indian",
 "Chinese Bhel", "Chinese",
 "Manhurian Soup", "Chinese",
 "Singapore Soup", "Chinese",
 "Chicken 65", "Chinese",
 "Chicken Crispy", "Cinese",
 "Chicken Manchurian", "Chinese",,
 "Egg Fried Rice", "Chinese",
 "Egg Fried Noodles", "Chinese",
 "Chicken Fried Rice", "Chinese",
 "Chicken Fried Noodles", "Chinese",
 "Chicken Triple Rice", "Chinese",
 "Chicken Triple Noodles", "Chinese",
 "Veg Triple Rice", "Chinese",
 "Veg Triple Noodles", "Chinese",
